name: axe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm run build --if-present
      - name: Start server if not running
        env:
         ESLINT_NO_DEV_ERRORS: 'true'
        run: |
          if ! curl -s http://localhost:3000 > /dev/null; then
            npm start &
            npx wait-on http://localhost:3000 &
            npm install -g @axe-core/cli 
            axe http://localhost:3000 --exit
          fi
          npm install -g @axe-core/cli
          axe http://localhost:3000 --exit