name: axe
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm run build --if-present
      - name: Check server and run axe
        run: |
          npm install -g @axe-core/cli
          if ! curl -s http://localhost:3000 > /dev/null; then
            npm start &
            npx wait-on http://localhost:3000
          fi
          axe http://localhost:3000 --exit
      - name: Archive axe accessibility report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: axe accessibility report 
          path: |
              public/a11y_reports