name: Lighthouse
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 'lts/*'
      - name: npm install, build
        run: |
            npm install
            npm run build
      - name: run Lighthouse CI
        run: |
            npm install -g @lhci/cli@0.7.x
            lhci autorun
