name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          record: true
          env:
          CYPRESS_RECORD_KEY: 3e425fe3-112b-40c9-87b9-c59895b1862d
          # pass GitHub token to allow accurately detecting a build vs a re-run build
