name: pa11y
on:
  workflow_run:
    workflows: ["axe"]
    types: 
      - completed
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - name: Build
        env:
          ESLINT_NO_DEV_ERRORS: 'true'
        run: npm run build --if-present
      - name: Start server if not running then run pa11y
        continue-on-error: true
        run: |
          if ! curl -s http://localhost:3000 > /dev/null; then
            npm start &
            npx wait-on http://localhost:3000 &
            npm install -g pa11y
            pa11y http://localhost:3000 
          fi
          npm install -g pa11y
          pa11y http://localhost:3000 
      - name: Archive pally accessibility report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: pally accessibility report 
          path: 
                public/a11y_reports