name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - name: Build
        env:
          ESLINT_NO_DEV_ERRORS: 'true'
        run: npm run build --if-present
      - name: Start server if not running then run pa11y
        run: |
          if ! curl -s http://localhost:3000 > /dev/null; then
            npm start &
            npx wait-on http://localhost:3000 &
            npm install -g pa11y
            axe http://localhost:3000 --exit
          fi
          npm install -g pa11y
          axe http://localhost:3000 --exit