name: Lighthouse
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'http://localhost:3000'