name: Lighthouse
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Start server if not running then run pa11y
      run: |
          if ! curl -s http://localhost:3000 > /dev/null; then
            npm start &
            npx wait-on http://localhost:3000
          fi
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'http://localhost:3000'